In [1]:
import numpy as np
import pandas as pd
import sklearn.neural_network as nn

In [2]:
train_data = pd.read_csv('train.csv')
Xtest = pd.read_csv('test.csv')

In [3]:
train_data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
Xtrain = train_data.drop(['label'],axis='columns')
Ytrain = train_data['label']

In [5]:
Xtrain.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
Ytrain.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [7]:
clf = nn.MLPClassifier(hidden_layer_sizes=5, activation='logistic', max_iter=1000, solver='sgd', tol=10**(-6), learning_rate_init=0.01)

In [8]:
clf.fit(Xtrain,Ytrain)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=5, learning_rate='constant',
              learning_rate_init=0.01, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='sgd',
              tol=1e-06, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [9]:
clf.score(Xtrain,Ytrain)

0.7228809523809524

In [10]:
try1 = clf.predict(Xtest)

In [12]:
clf.predict(Xtrain)

array([1, 0, 1, ..., 7, 6, 4])

In [11]:
#np.savetxt("Digit_predict.csv", try1, delimiter=",")